URL_BASE = r"/api"

URL_CONTEXT_FORECAST = "/forecast"

URL_REGEX_CLIENT_ID = fr"/(?P<clientid>\w+)"

VURI_FORECAST_CLIENT_ID = f"{URL_CONTEXT_FORECAST}{URL_REGEX_CLIENT_ID}"
VURI_FORECAST = f"{URL_CONTEXT_FORECAST}"
